# Site Info
title: 'Jeongjin Oh'
tagline: 'Jeongjin Oh'
description: 'Lazy Game Programmer <a href="https://github.com/Game-Pocket" target="_blank">@Game-Pocket</a>'
baseurl: ""
url: https://onsemy.me
logo: '/images/avatar.jpg'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jeongjin Oh
  description: <strong>Lazy Game Programmer <a href="https://github.com/Game-Pocket">@Game-Pocket</a></strong>
  # gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/onsemy
    github:    https://github.com/onsemy
    # facebook:  <hide>
    twitter:   https://twitter.com/onsemy
    # weibo:     http://weibo.com/41173780
    email:     mailto:onsemy@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
  Categories:
    - '/blog/categories/'
    - { Life: '/blog/categories/#life' }
    - { Study: '/blog/categories/#study' }
    - { Project: '/blog/categories/#project' }
    - { Review: '/blog/categories/#review' }
    - { Books: '/blog/categories/#books' }
  Tags:
    - '/blog/tags/'
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /images/home.gif
  caption: Welcome to ようこそ 온새미 집에!

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'onsemy' # leave blank if you don't want disqus

