title: Jeongjin Oh # name of the site
author: Jeongjin Oh # name of site's author
email: onsemy@gmail.com # email of site's author
url: https://onsemy.me # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  Lazy Game Programmer <a href="https://github.com/Game-Pocket" target="_blank">@Game-Pocket</a>.

permalink: pretty #/:slug.html

favicon: "/images/avatar.jpg" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

disqus_short_name: 'onsemy' # leave blank if you don't want disqus