# Setup
title: Jeongjin Oh
description: 🖖 Live Lazy And Programming
url: https://onsemy.me
paginate: 1
baseurl: "/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jeongjin Oh
  url: https://github.com/onsemy
  email: onsemy@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: About
    url: /about

  - title: GitHub
    url: https://github.com/onsemy

  - title: LinkedIn
    url: https://linkedin.com/in/onsemy

disqus_short_name: # leave blank if you don't want disqus
utterances:
  repo: onsemy/onsemy.me
